name: spout_social
description: "The Queer dWeb"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^3.1.0
  rinf: ^7.1.0
  image_picker: ^0.8.4+4
  fixnum: ^1.1.1
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  workmanager:
    git:
      url: https://github.com/absar/flutter_workmanager.git
      ref: ios-bg-tasks-enh-final
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
